if v:progname == 'vi'
  set noloadplugins
endif

" Leader mappings.
let mapleader = ","
let maplocalleader = "\\"

" fzf setup
set rtp+=/usr/local/opt/fzf

if &loadplugins
  if has('packages')
    packadd! deoplete  " Autocomplete
    packadd! deoplete-lsp " Deoplete LSP integration
    packadd! ferret " Improved multi-file search
    packadd! fzf.vim

    if has('nvim')
      packadd! nvim-lsp " Configurations for common language servers
    end

    packadd! pinnacle " Manipulate highlight groups for italics
    packadd! supertab              " Tab to complete
    packadd! terminus " Improved terminal integration
    packadd! vim-one " Light color scheme
    packadd! vim-clipper " Integrate MacOS clipboard the lazy way
    packadd! vim-dispatch " Async Git push
    packadd! vim-dispatch-neovim " Use neovim's terminal emulator
    packadd! vim-eunuch                " UNIX helpers including move and rename
    packadd! vim-fetch " Open files with line and column numbers
    packadd! vim-fugitive " Git integrations
    packadd! vim-signify " Git diff status in the gutter
    packadd! vim-surround             " Surrounding quotes and parens
    packadd! vim-tmux-navigator
    packadd! vimwiki " Organisation and notes
  else
    " TODO: implement fallback for normal vim, like pathogen
  end
end

" Automatic, language-dependent indentation, syntax coloring and other
" functionality.
"
" Must come *after* the `:packadd!` calls above otherwise the contents of
" package "ftdetect" directories won't be evaluated.
filetype indent plugin on
syntax on


" Messages, Info, Status
set laststatus=2            " allways show status line
set confirm                 " Y-N-C prompt if closing with unsaved changes.
set showcmd                 " Show incomplete normal mode commands as I type.
set report=0                " : commands always print changed line count.
set shortmess+=a            " Use [+]/[RO]/[w] for modified/readonly/written.
set ruler                   " Show some info, even without statuslines.
set laststatus=2            " Always show statusline, even if only 1 window.
set statusline=%<%f\ (%{&ft})%=%-19(%3l,%02c%03V%)

" Cursor
let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1

" Colors
colorscheme one
set background=light

" Vimwiki
au BufNewFile ~/Dropbox/vimwiki/diary/*.md :silent 0r !~/.config/nvim/bin/generate-vimiwiki-template.py '%'
