if v:progname == 'vi'
  set noloadplugins
endif

" Leader mappings.
let mapleader = ","
let maplocalleader = "\\"

" fzf setup
set rtp+=/opt/homebrew/opt/fzf

if &loadplugins
  if has('packages')
    packadd! ferret " Improved multi-file search
    packadd! fzf.vim

    if has('nvim')
      packadd! nvim-compe
      packadd! nvim-lspconfig     " Configurations for common language servers
      packadd! nvim-neomake       " Async linting
    end

    packadd! pinnacle             " Manipulate highlight groups for italics
    packadd! supertab             " Tab to complete
    packadd! terminus             " Improved terminal integration
    packadd! vimwiki              " Organisation and notes
    " packadd! vim-one              " Light color scheme
    packadd! vim-clipper          " Integrate MacOS clipboard the lazy way
    packadd! vim-dispatch         " Async Git push
    packadd! vim-dispatch-neovim  " Use neovim's terminal emulator
    packadd! vim-eunuch           " UNIX helpers including move and rename
    packadd! vim-fetch            " Open files with line and column numbers
    packadd! vim-fugitive         " Git integrations
    packadd! vim-git
    packadd! vim-go
    packadd! vim-javascript
    packadd! vim-json
    packadd! vim-markdown
    packadd! vim-signify          " Git diff status in the gutter
    packadd! vim-sleuth           " Automatically set shiftwidth and expandtab
    packadd! vim-surround         " Surrounding quotes and parens
    packadd! vim-tmux-navigator
    packadd! vim-yaml
  else
    " TODO: implement fallback for normal vim, like pathogen
  end
end

" Automatic, language-dependent indentation, syntax coloring and other
" functionality.
"
" Must come *after* the `:packadd!` calls above otherwise the contents of
" package "ftdetect" directories won't be evaluated.
filetype indent plugin on
syntax on
