#!/bin/bash
# Extracts one password secrets for SSH, GPG, GitLab and GitHub
set -e

if ! [ -L ~/.gnupg ] || ! [ -L ~/.ssh ]
then
  echo "Run script/setup first!" >&2
  exit 1
fi

onepassword_login() {
  if ! command -v op >/dev/null
  then
    echo "Install op first!" >&2
    exit 1
  fi

  # shellcheck disable=SC2154
  if [ -z "$OP_SESSION_jramsay" ]
  then
    echo "Logging into 1Password..."
    eval "$(op signin ramsays.1password.com james@jramsay.com.au)"
  fi
}

onepassword_get() {
  if [ -f "$HOME/$2" ]
  then
    echo "$2 already exists."
    return
  fi
  echo "Extracting $2..."
  onepassword_login
  op get document "$1" > "$HOME/$2"
  chmod 600 "$HOME/$2"
}

onepassword_get 6fr2qdnuvlvicsqspderlky27a .ssh/id_rsa
onepassword_get ouxclgyjnngqxatqij7xlbrvxi .gnupg/james@jramsay.com.au.private-subkeys.gpg

if ! [ -f "$HOME/.secrets" ]
then
  echo "Extracting secrets..."
  if ! command -v jq >/dev/null
  then
    echo "Install jq first!" >&2
    exit 1
  fi
  onepassword_login
  GITHUB_TOKEN=$(op get item pmynxpo2tbctrbwqhvjomftdbq | jq -r '.details.sections[].fields[]? | select(.t=="access token") | .v')
  GITLAB_TOKEN=$(op get item 4egeaihs4jbrlnbpwealxvbvpe | jq -r '.details.sections[].fields[]? | select(.t=="access token") | .v')
  cat > "$HOME/.secrets" <<EOF
export GITHUB_TOKEN=$GITHUB_TOKEN
export GITLAB_TOKEN=$GITLAB_TOKEN
EOF
  chmod 600 "$HOME/.secrets"
fi

echo "Storing SSH keys in keychain..."
ssh-add -K

echo "Setting up GPG..."
if ! command -v gpg >/dev/null
then
    echo "Install GPG first!" >&2
    exit 1
fi

chmod 700 ~/.gnupg
gpg --import ~/.gnupg/james@jramsay.com.au.public.gpg-key \
             ~/.gnupg/james@jramsay.com.au.private-subkeys.gpg-key

