#!/bin/bash
# Completes the configuration of vim

# symlink nvim to vim
rm -rv "$HOME/.config/nvim"
ln -sv "$HOME/.vim" "$HOME/.config/nvim"

# download vim-plug
curl -fLo "$HOME/.vim/autoload/plug.vim" --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
