---
- name: iterm2 | link preferences
  file: src={{ ansible_env.PWD }}/roles/iterm2/files
        path=~/.iterm2
        state=link
        force=yes

- name: iterm2 | set preferences directory
  osx_defaults:
    domain: com.googlecode.iterm2
    key: PrefsCustomFolder
    type: string
    value: ~/.iterm2

- name: iterm2 | load preferences from directory
  osx_defaults:
    domain: com.googlecode.iterm2
    key: LoadPrefsFromCustomFolder
    type: boolean
    value: true
