name: docgen

on: [push]

jobs:
  docgen:
    runs-on: [ubuntu-latest]
    if: github.ref != 'master'
    steps:
    - uses: actions/checkout@v2
    - run: date +%F > todays-date
    - name: Restore cache for today's nightly.
      uses: actions/cache@v1.0.0
      with:
        path: _neovim
        key: ${{ runner.os }}-nightly-${{ hashFiles('todays-date') }}
    - name: Setup from neovim nightly and run docgen
      run: |
        curl -OL https://raw.githubusercontent.com/norcalli/bot-ci/master/scripts/github-actions-setup.sh
        source github-actions-setup.sh nightly-x64
        scripts/docgen.sh
    - name: Commit changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MSG: |
          [docgen] Update README.md
          skip-checks: true
      run: |
        git config user.email "actions@github"
        git config user.name "Github Actions"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git add README.md
        # Only commit and push if we have changes
        git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin HEAD:${GITHUB_REF})
